name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
    steps:
    # チェックアウト
    - uses: actions/checkout@v1
    
    # ビルド
    - name: Xcode build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration DevelopDebug
        -workspace Every.xcworkspace
        -scheme Every_Develop
        build

    # # 単体テストの実行
    - name: Xcode test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace Every.xcworkspace
        -scheme Every_Develop
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
        clean test
