name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
    steps:
    # チェックアウト
    - uses: actions/checkout@v1
    
    - name: Select Xcode version # Xcode 11.3 を使う
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Build # シミュレーター向けにビルド
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 
    
    # ビルド
    - name: Xcode build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme TestProject
        build

    # # 単体テストの実行
    - name: Xcode test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme TestProject
        clean test
